"""An Apify Actor around an approved core build, and its Store listing - deterministic.

The night builds produce the CORE (a standard-library Python package with ``process(record)``,
reviewed by Claude, no network). This module writes everything around it from the spec, the
same way every time, so nothing here is model-written code:

- ``.actor/actor.json``, ``.actor/input_schema.json``, ``.actor/Dockerfile`` (the official
  ``apify/actor-python`` image), ``requirements.txt`` (the Apify SDK and httpx);
- ``src/main.py`` - the wrapper: reads the input, fetches each URL (``io=fetch_urls``) or takes
  each JSON item (``io=items``), calls ``process`` on ONE record at a time, stores every result
  and charges ONE pay-per-event event per result WITHOUT an ``error`` (a failed record is
  stored and not charged), and stops at the run's spending limit;
- ``README.md`` - the Store page, built from the spec's checked words (what it does, the
  features, input, output, the exact price, the honest limits, and how it was made);
- the core package itself (``src/<package>/``) and its licence files.

The listing (``listing.json``) is exactly the ``apify.publish`` payload.
"""
from __future__ import annotations

import hashlib
import io
import json
import zipfile

from pionir.adapters.marketplace_listing import claim_problems

from ..builds.package import STAMP
from . import images

VERSION = "0.1"
PACKAGE = "actor-source.zip"
ICON = "icon.png"
SDK = "apify>=2.3,<4"
HTTPX = "httpx>=0.27,<1"
DISCLOSURE = ("The core of this Actor was written by an AI coding system; its tests were run "
              "and the code was reviewed before release.")
LISTING_KEYS = frozenset({"slug", "actor_name", "title", "description", "seo_title",
                          "seo_description", "categories", "version", "pricing",
                          "package_name", "package_sha256", "files", "readme_md",
                          "icon_name", "icon_sha256"})

DOCKERFILE = """FROM apify/actor-python:3.12

USER myuser
COPY --chown=myuser:myuser requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=myuser:myuser . ./
RUN python3 -m compileall -q src/
CMD ["python3", "-m", "src"]
"""

MAIN_PY = '''"""The Apify Actor around {name}.

Generated by the packager from the product's spec (never model-written): it reads the input,
{how}, hands ONE record at a time to the core's process(), stores every result and charges
one "{event}" event for each result without an "error" key. A record that fails is stored
with its error and is not charged.
"""
from __future__ import annotations

import os
import sys

from apify import Actor

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from {package} import process  # noqa: E402 - the core lives beside this file

EVENT = "{event}"
MAX_TEXT = 5_000_000
DEFAULT_MAX = 100


def _limit(actor_input: dict) -> int:
    value = actor_input.get("maxItems")
    return value if isinstance(value, int) and value > 0 else DEFAULT_MAX


def _urls(actor_input: dict) -> list:
    out = []
    for item in actor_input.get("startUrls") or []:
        url = item.get("url") if isinstance(item, dict) else item
        if isinstance(url, str) and url.startswith(("http://", "https://")):
            out.append(url)
    return out


async def _fetch(client, url: str) -> dict:
    try:
        response = await client.get(url, follow_redirects=True, timeout=30.0)
        return {{"url": str(response.url), "status": response.status_code,
                "content_type": response.headers.get("content-type", ""),
                "text": response.text[:MAX_TEXT]}}
    except Exception as exc:  # noqa: BLE001 - one bad URL must not stop the run
        Actor.log.warning(f"could not fetch {{url}}: {{type(exc).__name__}}")
        return {{"url": url, "status": 0, "content_type": "", "text": "",
                "fetch_error": f"{{type(exc).__name__}}: {{exc}}"[:300]}}


def _run_core(record: dict) -> dict:
    try:
        result = process(record)
    except Exception as exc:  # noqa: BLE001 - stored as an error, never charged
        return {{"error": f"{{type(exc).__name__}}: {{exc}}"[:300]}}
    if not isinstance(result, dict):
        return {{"error": "the core returned something that is not an object"}}
    return result


async def _emit(result: dict) -> bool:
    """Store one result; charge it when it has no error. False: stop the run."""
    await Actor.push_data(result)
    if "error" in result:
        return True
    charged = await Actor.charge(event_name=EVENT)
    if charged.event_charge_limit_reached:
        Actor.log.info("the run's spending limit is reached; stopping")
        return False
    return True


async def main() -> None:
    async with Actor:
        actor_input = await Actor.get_input() or {{}}
        limit = _limit(actor_input)
{body}
'''

BODY_FETCH = '''        import httpx

        urls = _urls(actor_input)[:limit]
        if not urls:
            await Actor.fail(status_message="no URLs in startUrls")
            return
        async with httpx.AsyncClient(headers={"User-Agent": "Mozilla/5.0 (Apify Actor)"}) \\
                as client:
            for url in urls:
                if not await _emit(_run_core(await _fetch(client, url))):
                    break
'''

BODY_ITEMS = '''        items = [x for x in (actor_input.get("items") or []) if isinstance(x, dict)][:limit]
        if not items:
            await Actor.fail(status_message="no JSON objects in items")
            return
        for item in items:
            if not await _emit(_run_core(item)):
                break
'''

MAIN_ENTRY = '''import asyncio

from .main import main

asyncio.run(main())
'''

THIRD_PARTY = """Third-party parts used by this Actor
====================================

The core package (src/{package}/) uses only the Python standard library.
The Actor wrapper (src/main.py) is installed with, and runs on:
- apify (the Apify SDK for Python), Apache License 2.0
- httpx, BSD 3-Clause License
- the apify/actor-python Docker image
"""


def short_title(name: str) -> str:
    t = name.split(":", 1)[0].strip()
    return t if len(t) <= 60 else t[:57].rsplit(" ", 1)[0] + "..."


def _clip_words(text: str, n: int) -> str:
    text = " ".join(text.split())
    if len(text) <= n:
        return text
    return text[:n - 3].rsplit(" ", 1)[0].rstrip(",;:") + "..."


def input_schema(spec: dict) -> dict:
    title = short_title(spec["name"])
    limit = {"title": "Maximum results", "type": "integer", "default": 100, "minimum": 1,
             "maximum": 10000,
             "description": "Stop after this many results (each successful one is charged)."}
    if spec["listing"]["io"] == "fetch_urls":
        props = {"startUrls": {"title": "URLs", "type": "array", "editor": "requestListSources",
                               "description": "The pages to process: one result per page.",
                               "prefill": [{"url": "https://example.com"}]},
                 "maxItems": limit}
        required = ["startUrls"]
    else:
        props = {"items": {"title": "Items", "type": "array", "editor": "json",
                           "description": "The JSON objects to process: one result each.",
                           "prefill": [{}]},
                 "maxItems": limit}
        required = ["items"]
    return {"title": f"{title} input", "type": "object", "schemaVersion": 1,
            "properties": props, "required": required}


def readme(spec: dict) -> str:
    lst, ev = spec["listing"], spec["listing"]["event"]
    features = "\n".join(f"- {f}" for f in spec["features"])
    if lst["io"] == "fetch_urls":
        given = ("A list of URLs (`startUrls`). The Actor fetches each page once and processes "
                 "it; a page that cannot be fetched gives a result with an `error`.")
    else:
        given = "A JSON array of objects (`items`); each is processed on its own."
    per_k = float(ev["price_usd"]) * 1000
    return (f"# {short_title(spec['name'])}\n\n{spec['summary']}\n\n## What it does\n\n"
            f"{spec['brief']}\n\n## Features\n\n{features}\n\n## Input\n\n{given} "
            "`maxItems` caps the number of results.\n\n## Output\n\nOne dataset item per "
            "input. A record that could not be processed is stored with an `error` field.\n\n"
            f"## Pricing\n\nPay per event: **${float(ev['price_usd']):.4f} per successful result** "
            f"(\"{ev['title']}\": {ev['description']}) - ${per_k:.2f} per 1,000 results - plus "
            "Apify's standard Actor start event. Results with an `error` are not charged.\n\n"
            f"## Limits\n\n{spec['limits']}\n\n## How it was made\n\n{DISCLOSURE}\n")


def _zip(files: dict) -> bytes:
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w") as zf:
        for rel in sorted(files):
            info = zipfile.ZipInfo(rel, date_time=STAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            zf.writestr(info, files[rel], compress_type=zipfile.ZIP_DEFLATED, compresslevel=9)
    return out.getvalue()


def source_files(spec: dict, core: dict) -> dict:
    """{path: bytes} of the whole Actor: the core's package and licence, and the wrapper."""
    pkg = spec["package"]
    lst = spec["listing"]
    out: dict = {}
    prefix = f"src/{pkg}/"
    for rel, data in core.items():
        if rel.startswith(prefix) and not rel.endswith((".pyc", ".pyo")):
            out[rel] = data
    if f"{prefix}__init__.py" not in out:
        raise ValueError(f"the build has no {prefix}__init__.py: there is no core to wrap")
    for rel in ("LICENSE.txt",):
        if rel in core:
            out[rel] = core[rel]
    if "README.md" in core:
        out["docs/CORE.md"] = core["README.md"]
    how = ("fetches each URL it is given" if lst["io"] == "fetch_urls"
           else "takes each JSON item it is given")
    out["src/main.py"] = MAIN_PY.format(
        name=short_title(spec["name"]), how=how, event=lst["event"]["name"], package=pkg,
        body=BODY_FETCH if lst["io"] == "fetch_urls" else BODY_ITEMS).encode()
    out["src/__main__.py"] = MAIN_ENTRY.encode()
    out["requirements.txt"] = (SDK + "\n" + (HTTPX + "\n" if lst["io"] == "fetch_urls"
                                             else "")).encode()
    out["THIRD_PARTY.txt"] = THIRD_PARTY.format(package=pkg).encode()
    out[".actor/Dockerfile"] = DOCKERFILE.encode()
    out[".actor/input_schema.json"] = (json.dumps(input_schema(spec), indent=2) + "\n").encode()
    out[".actor/actor.json"] = (json.dumps({
        "actorSpecification": 1, "name": spec["slug"], "title": short_title(spec["name"]),
        "description": spec["summary"], "version": VERSION, "buildTag": "latest",
        "input": "./input_schema.json", "dockerfile": "./Dockerfile"}, indent=2) + "\n").encode()
    out["README.md"] = readme(spec).encode()
    return out


def draft(spec: dict, core: dict) -> tuple:
    """``(listing, {file name: bytes}, problems)``: the listing.json, the files to write
    beside it (the source zip and the icon), and every reason it may not be submitted."""
    files = source_files(spec, core)
    package = _zip(files)
    icon = images.icon(spec["name"], 512)
    ev = spec["listing"]["event"]
    text = readme(spec)
    listing = {
        "slug": spec["slug"], "actor_name": spec["slug"], "title": short_title(spec["name"]),
        "description": _clip_words(spec["summary"], 300),
        "seo_title": short_title(spec["name"]),
        "seo_description": _clip_words(spec["summary"], 156),
        "categories": list(spec["listing"]["categories"]), "version": VERSION,
        "pricing": {"model": "PAY_PER_EVENT", "event_name": ev["name"],
                    "event_title": ev["title"], "event_description": ev["description"],
                    "price_usd": float(ev["price_usd"])},
        "package_name": PACKAGE, "package_sha256": hashlib.sha256(package).hexdigest(),
        "files": sorted(files), "readme_md": text, "icon_name": ICON,
        "icon_sha256": hashlib.sha256(icon).hexdigest()}
    problems = claim_problems({"title": listing["title"], "description": listing["description"],
                               "readme_md": text})
    return listing, {PACKAGE: package, ICON: icon}, problems
