"""The API builder's backlog: each product on paper, owner-editable, checked, fail closed.

``<apibuilds_dir>/backlog.json`` is ``{"version": 1, "entries": [...]}``. The owner edits it by
hand (add, remove, reorder, ``"retry": n`` to reopen a shelved product); the worker only ever
READS it after the first run, which writes the seed. An entry is the whole product on paper:

``id`` (lowercase letters: it is the path segment under /v1/), ``name``, ``summary``,
``endpoints`` (method, path, description, an example request and response), ``limits`` (what
the docs will state), and ``why`` (who searches for it). Optional: ``validated`` (default
false - the seeds are guesses until the traffic says otherwise), ``priority`` (higher builds
first; ties keep file order), ``state`` (``queued`` or ``removed``), ``retry`` (an integer;
raising it reopens a shelved product).

Every customer-facing word is the entry's own, so it is checked here: no model words, no
control characters, bounded. An entry that fails is reported with its reasons and never built.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from pionir import atomic
from ..blog import _clip
from ..log import log

BACKLOG_FILE = "backlog.json"
ID = re.compile(r"[a-z]{3,20}")
# every product that already answers under /v1/ in Scrooge, and the words the router and the
# docs own: a new product may not shadow one
RESERVED_IDS = frozenset({
    "invoice", "email", "site", "text", "qr", "barcode", "pdf", "convert", "calendar", "image",
    "health", "openapi", "docs", "keys", "key", "usage", "plans", "uptime", "hire", "city",
    "dash", "admin", "stripe", "webhook", "fiverr", "blog", "traffic", "status", "ping",
})
METHODS = ("GET", "POST")
MAX_ENTRIES = 50
MAX_ENDPOINTS = 6
MAX_LIMITS = 8
NAME_MAX, SUMMARY_MAX, TEXT_MAX, EXAMPLE_MAX, WHY_MAX = 60, 240, 400, 600, 400
# words that must never reach a customer, in the backlog's copy or in the built file
MODEL_WORDS = re.compile(
    r"\b(claude|anthropic|openai|chatgpt|gpt-?\d*|llm|llms|language model|as an ai|"
    r"ai[- ]generated|generated by ai|large language)\b", re.IGNORECASE)
_CONTROL = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def _seed() -> list:
    def e(id_, name, summary, endpoints, limits, why):
        return {"id": id_, "name": name, "summary": summary, "endpoints": endpoints,
                "limits": limits, "why": why, "validated": False, "source": "seed",
                "state": "queued", "priority": 0, "retry": 0}

    def ep(method, path, description, request, response):
        return {"method": method, "path": path, "description": description,
                "example_request": request, "example_response": response}

    return [
        e("colour", "Colour API",
          "WCAG contrast ratio and pass/fail for any two colours, and conversion between hex, "
          "rgb and hsl, from one GET.",
          [ep("GET", "/v1/colour/contrast",
              "Contrast ratio of two colours (fg, bg as hex) and whether it passes WCAG AA and "
              "AAA for normal and large text.",
              "GET /v1/colour/contrast?fg=767676&bg=ffffff",
              '{"ratio":4.54,"aa":{"normal":true,"large":true},'
              '"aaa":{"normal":false,"large":true}}'),
           ep("GET", "/v1/colour/convert",
              "Convert one colour (hex, rgb() or hsl()) to all three notations.",
              "GET /v1/colour/convert?value=%23ff8800",
              '{"hex":"#ff8800","rgb":[255,136,0],"hsl":[32,100,50]}')],
          ["hex colours in #rgb or #rrggbb form",
           "rgb() and hsl() with integer or decimal values",
           "no colour names, no alpha channel"],
          "Accessibility checkers, design-token tools and CMS themes search for a hosted WCAG "
          "contrast check they can call from a build step."),
        e("cron", "Cron API",
          "The next run times of a cron expression in any time zone, with a plain-English "
          "reading of the schedule.",
          [ep("GET", "/v1/cron/next",
              "The next runs (count, 1 to 20) of a five-field cron expression from a start "
              "time, in an IANA time zone.",
              "GET /v1/cron/next?expr=0%209%20*%20*%201-5&tz=Europe%2FLondon&count=3",
              '{"expr":"0 9 * * 1-5","tz":"Europe/London","next":["2026-10-01T09:00:00+01:00"]}'),
           ep("GET", "/v1/cron/explain",
              "A plain-English reading of a five-field cron expression.",
              "GET /v1/cron/explain?expr=0%209%20*%20*%201-5",
              '{"expr":"0 9 * * 1-5","text":"At 09:00, Monday to Friday"}')],
          ["five fields only (minute hour day month weekday)",
           "lists, ranges and steps; no names like MON or JAN", "at most 20 runs per call"],
          "Developers writing schedulers and CI configs search for a way to check what a cron "
          "line really does, and for when it will next fire."),
        e("validate", "Validate API",
          "Structure and check-digit validation for IBANs, card numbers (Luhn) and ISBN-10 or "
          "ISBN-13, with a clear reason when one fails.",
          [ep("POST", "/v1/validate/iban",
              "Check an IBAN's country length, characters and mod-97 check digits.",
              'POST /v1/validate/iban {"value":"GB82 WEST 1234 5698 7654 32"}',
              '{"valid":true,"country":"GB","normalised":"GB82WEST12345698765432"}'),
           ep("POST", "/v1/validate/luhn",
              "Check a number's Luhn check digit (card numbers, IMEI and similar).",
              'POST /v1/validate/luhn {"value":"4539 1488 0343 6467"}',
              '{"valid":true,"length":16}'),
           ep("POST", "/v1/validate/isbn",
              "Check an ISBN-10 or ISBN-13 check digit.",
              'POST /v1/validate/isbn {"value":"978-0-306-40615-7"}',
              '{"valid":true,"kind":"isbn13"}')],
          ["format and check digit only: a valid number is well formed, not proof that an "
           "account or book exists", "values are not stored or logged",
           "at most 64 characters"],
          "Checkout and onboarding forms search for a quick server-side IBAN and card-number "
          "format check before they call a bank or payment provider."),
        e("semver", "Semver API",
          "Compare two semantic versions, test a version against a range, and pick the highest "
          "version that satisfies a range from a list.",
          [ep("GET", "/v1/semver/compare",
              "Compare two versions: -1, 0 or 1, and which is newer.",
              "GET /v1/semver/compare?a=1.2.0&b=1.10.0",
              '{"result":-1,"newer":"1.10.0"}'),
           ep("POST", "/v1/semver/satisfies",
              "Which of a list of versions satisfy a range such as ^1.2.0 or >=2 <3, and the "
              "highest one.",
              'POST /v1/semver/satisfies {"range":"^1.2.0","versions":["1.1.0","1.4.2","2.0.0"]}',
              '{"matching":["1.4.2"],"highest":"1.4.2"}')],
          ["semver 2.0.0 versions, with optional pre-release and build parts",
           "ranges: exact, ^, ~, comparison operators and space-separated AND sets",
           "at most 200 versions per call"],
          "Release tooling and dependency dashboards search for a hosted semver comparison so "
          "they need not bundle a library in every script."),
    ]


@dataclass
class Backlog:
    """What the file holds: the entries that passed, in build order, and each that did not."""

    entries: list = field(default_factory=list)
    invalid: list = field(default_factory=list)       # [(id-or-index, [reasons])]
    seeded: bool = False


def _text(value, limit: int, what: str, reasons: list, *, minimum: int = 1) -> str:
    if not isinstance(value, str) or not minimum <= len(value.strip()) <= limit:
        reasons.append(f"{what} must be text of {minimum} to {limit} characters")
        return ""
    if _CONTROL.search(value):
        reasons.append(f"{what} has control characters")
    if MODEL_WORDS.search(value):
        reasons.append(f"{what} names a model or an AI vendor, which never reaches a customer")
    return value


def check_entry(entry) -> list:
    """Why this entry cannot be built (empty: it can). Fail closed: anything not understood
    is a reason."""
    if not isinstance(entry, dict):
        return ["the entry is not an object"]
    reasons: list = []
    pid = entry.get("id")
    if not isinstance(pid, str) or not ID.fullmatch(pid):
        reasons.append("id must be 3 to 20 lowercase letters (it is the path under /v1/)")
        pid = None
    elif pid in RESERVED_IDS:
        reasons.append(f"id {pid!r} is already a product or a reserved word")
    _text(entry.get("name"), NAME_MAX, "name", reasons)
    _text(entry.get("summary"), SUMMARY_MAX, "summary", reasons, minimum=20)
    _text(entry.get("why"), WHY_MAX, "why", reasons, minimum=20)
    endpoints = entry.get("endpoints")
    if not isinstance(endpoints, list) or not 1 <= len(endpoints) <= MAX_ENDPOINTS:
        reasons.append(f"endpoints must be a list of 1 to {MAX_ENDPOINTS}")
        endpoints = []
    seen = set()
    for i, ep in enumerate(endpoints):
        where = f"endpoint {i + 1}"
        if not isinstance(ep, dict):
            reasons.append(f"{where} is not an object")
            continue
        method, path = ep.get("method"), ep.get("path")
        if method not in METHODS:
            reasons.append(f"{where}: method must be GET or POST")
        if not isinstance(path, str) or pid is None or not re.fullmatch(
                rf"/v1/{pid}(/[a-z0-9-]+)*", path):
            reasons.append(f"{where}: path must be /v1/{pid or '<id>'} then lowercase "
                           "segments")
        elif (method, path) in seen:
            reasons.append(f"{where}: {method} {path} is listed twice")
        else:
            seen.add((method, path))
        _text(ep.get("description"), TEXT_MAX, f"{where} description", reasons, minimum=10)
        _text(ep.get("example_request"), EXAMPLE_MAX, f"{where} example_request", reasons)
        _text(ep.get("example_response"), EXAMPLE_MAX, f"{where} example_response", reasons)
    limits = entry.get("limits")
    if not isinstance(limits, list) or not 1 <= len(limits) <= MAX_LIMITS:
        reasons.append(f"limits must be a list of 1 to {MAX_LIMITS} statements")
    else:
        for i, text in enumerate(limits):
            _text(text, 200, f"limit {i + 1}", reasons)
    for key, kind in (("validated", bool), ("priority", int), ("retry", int)):
        value = entry.get(key, kind())
        if not isinstance(value, kind) or (kind is int and isinstance(value, bool)):
            reasons.append(f"{key} must be "
                           f"{'true or false' if kind is bool else 'a whole number'}")
    if entry.get("state", "queued") not in ("queued", "removed"):
        reasons.append("state must be queued or removed")
    return reasons


def parse_backlog(doc) -> Backlog:
    """Entries in build order: valid and queued only, by priority (high first), file order for
    ties. An invalid entry is reported, never built; ``removed`` is skipped quietly."""
    out = Backlog()
    raw = doc.get("entries") if isinstance(doc, dict) else None
    if not isinstance(raw, list):
        out.invalid.append(("backlog", ["the file has no entries list"]))
        return out
    seen: set = set()
    good: list = []
    for i, entry in enumerate(raw[:MAX_ENTRIES]):
        label = entry.get("id") if isinstance(entry, dict) and isinstance(entry.get("id"), str) \
            else f"#{i + 1}"
        if isinstance(entry, dict) and entry.get("state") == "removed":
            continue
        reasons = check_entry(entry)
        if not reasons and entry["id"] in seen:
            reasons = [f"id {entry['id']!r} appears twice"]
        if reasons:
            out.invalid.append((_clip(label, 30), [_clip(r, 160) for r in reasons[:6]]))
            continue
        seen.add(entry["id"])
        good.append((i, entry))
    if len(raw) > MAX_ENTRIES:
        out.invalid.append(("backlog", [f"only the first {MAX_ENTRIES} entries are read"]))
    good.sort(key=lambda p: (-int(p[1].get("priority", 0)), p[0]))
    out.entries = [e for _i, e in good]
    return out


def load_backlog(directory, *, write_seed: bool = True) -> Backlog:
    """Read ``<directory>/backlog.json``. Missing: the seed is written (once) and returned.
    Unreadable or not JSON: ``ValueError`` - never overwritten, never guessed."""
    path = Path(directory) / BACKLOG_FILE
    if not path.exists():
        seed = {"version": 1, "entries": _seed(),
                "note": "Seed ideas are UNVALIDATED guesses. Edit freely: add, remove "
                        "(state: removed), reorder (priority), or set validated: true when "
                        "traffic says an idea is wanted."}
        if write_seed:
            path.parent.mkdir(parents=True, exist_ok=True)
            tmp = path.with_suffix(".tmp")
            tmp.write_text(json.dumps(seed, indent=1), encoding="utf-8")
            atomic.replace(tmp, path)
            log.info("api_builder: wrote the seed backlog to %s", path)
        out = parse_backlog(seed)
        out.seeded = True
        return out
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ValueError(f"{path} cannot be read ({exc})") from exc
    return parse_backlog(doc)
